// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyEntityType string

const (
	CompanyEntityTypeLEGALENTITY    CompanyEntityType = "LEGAL_ENTITY"
	CompanyEntityTypeSOLEPROPRIETOR CompanyEntityType = "SOLE_PROPRIETOR"
)

func (e *CompanyEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyEntityType(s)
	case string:
		*e = CompanyEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyEntityType: %T", src)
	}
	return nil
}

type NullCompanyEntityType struct {
	CompanyEntityType CompanyEntityType
	Valid             bool // Valid is true if CompanyEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyEntityType), nil
}

type CustomFieldType string

const (
	CustomFieldTypeTEXT    CustomFieldType = "TEXT"
	CustomFieldTypeNUMBER  CustomFieldType = "NUMBER"
	CustomFieldTypeDATE    CustomFieldType = "DATE"
	CustomFieldTypeBOOLEAN CustomFieldType = "BOOLEAN"
	CustomFieldTypeSELECT  CustomFieldType = "SELECT"
)

func (e *CustomFieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomFieldType(s)
	case string:
		*e = CustomFieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomFieldType: %T", src)
	}
	return nil
}

type NullCustomFieldType struct {
	CustomFieldType CustomFieldType
	Valid           bool // Valid is true if CustomFieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.CustomFieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomFieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomFieldType), nil
}

type DuplicateTaxNumberPolicy string

const (
	DuplicateTaxNumberPolicyALLOW DuplicateTaxNumberPolicy = "ALLOW"
	DuplicateTaxNumberPolicyWARN  DuplicateTaxNumberPolicy = "WARN"
	DuplicateTaxNumberPolicyBLOCK DuplicateTaxNumberPolicy = "BLOCK"
)

func (e *DuplicateTaxNumberPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DuplicateTaxNumberPolicy(s)
	case string:
		*e = DuplicateTaxNumberPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for DuplicateTaxNumberPolicy: %T", src)
	}
	return nil
}

type NullDuplicateTaxNumberPolicy struct {
	DuplicateTaxNumberPolicy DuplicateTaxNumberPolicy
	Valid                    bool // Valid is true if DuplicateTaxNumberPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDuplicateTaxNumberPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.DuplicateTaxNumberPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DuplicateTaxNumberPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDuplicateTaxNumberPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DuplicateTaxNumberPolicy), nil
}

type PartyKind string

const (
	PartyKindPERSON       PartyKind = "PERSON"
	PartyKindORGANIZATION PartyKind = "ORGANIZATION"
)

func (e *PartyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartyKind(s)
	case string:
		*e = PartyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PartyKind: %T", src)
	}
	return nil
}

type NullPartyKind struct {
	PartyKind PartyKind
	Valid     bool // Valid is true if PartyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartyKind) Scan(value interface{}) error {
	if value == nil {
		ns.PartyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartyKind), nil
}

type PartyRiskPolicy string

const (
	PartyRiskPolicyALLOW PartyRiskPolicy = "ALLOW"
	PartyRiskPolicyWARN  PartyRiskPolicy = "WARN"
	PartyRiskPolicyBLOCK PartyRiskPolicy = "BLOCK"
)

func (e *PartyRiskPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartyRiskPolicy(s)
	case string:
		*e = PartyRiskPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for PartyRiskPolicy: %T", src)
	}
	return nil
}

type NullPartyRiskPolicy struct {
	PartyRiskPolicy PartyRiskPolicy
	Valid           bool // Valid is true if PartyRiskPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartyRiskPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.PartyRiskPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartyRiskPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartyRiskPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartyRiskPolicy), nil
}

type ProductKind string

const (
	ProductKindPHYSICAL ProductKind = "PHYSICAL"
	ProductKindSERVICE  ProductKind = "SERVICE"
)

func (e *ProductKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductKind(s)
	case string:
		*e = ProductKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductKind: %T", src)
	}
	return nil
}

type NullProductKind struct {
	ProductKind ProductKind
	Valid       bool // Valid is true if ProductKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductKind) Scan(value interface{}) error {
	if value == nil {
		ns.ProductKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductKind), nil
}

type ApiToken struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	TokenPrefix string
	TokenHash   []byte
	Scopes      []string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type ApiTokenBranchScope struct {
	CompanyID pgtype.UUID
	TokenID   pgtype.UUID
	BranchID  pgtype.UUID
}

type ApiTokenWarehouseScope struct {
	CompanyID   pgtype.UUID
	TokenID     pgtype.UUID
	WarehouseID pgtype.UUID
}

type AssetAssignment struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	AssetID        pgtype.UUID
	EmployeeID     pgtype.UUID
	AssignedAt     pgtype.Timestamptz
	ReturnedAt     pgtype.Timestamptz
	AssignmentNote string
	ReturnNote     pgtype.Text
	AssignedBy     pgtype.UUID
	ReturnedBy     pgtype.UUID
	ActorSnapshot  []byte
	CreatedAt      pgtype.Timestamptz
}

type Branch struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type CommandIdempotencyRecord struct {
	CompanyID       pgtype.UUID
	IdempotencyKey  string
	CommandName     string
	PayloadSha256   string
	Status          string
	ResponseStatus  pgtype.Int2
	ResponseBody    []byte
	ResponseHeaders []byte
	ActorUserID     pgtype.UUID
	TraceID         pgtype.Text
	CreatedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
}

type CommercialDocumentSequence struct {
	CompanyID        pgtype.UUID
	DocumentTypeCode string
	SequenceYear     int32
	NextValue        int64
	UpdatedAt        pgtype.Timestamptz
}

type CommercialDocumentSource struct {
	CompanyID        pgtype.UUID
	DocumentID       pgtype.UUID
	SourceDocumentID pgtype.UUID
	RelationType     string
	CreatedAt        pgtype.Timestamptz
}

type CommercialEffectClaim struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	EffectKey  string
	EffectType string
	DocumentID pgtype.UUID
	LineID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type CommercialLineAllocation struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	SourceLineID   pgtype.UUID
	TargetLineID   pgtype.UUID
	AllocationType string
	Quantity       pgtype.Numeric
	BaseQuantity   pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	Status         string
}

type CommercialLineRegistry struct {
	CompanyID     pgtype.UUID
	LineID        pgtype.UUID
	AggregateType string
	DocumentID    pgtype.UUID
	LineNo        int32
	LineType      string
	Quantity      pgtype.Numeric
	BaseQuantity  pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type CommercialPartySnapshot struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	DocumentID     pgtype.UUID
	PartyCode      string
	DisplayName    string
	LegalName      string
	TaxNumber      string
	IdentityNumber string
	TaxOffice      string
	TaxOfficeCode  string
	Addresses      []byte
	SnapshotAt     pgtype.Timestamptz
}

type CommercialStatusHistory struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	AggregateType string
	DocumentID    pgtype.UUID
	FromStatus    pgtype.Text
	ToStatus      string
	Reason        string
	ActorUserID   pgtype.UUID
	OccurredAt    pgtype.Timestamptz
}

type Company struct {
	ID                              pgtype.UUID
	LegalName                       string
	TradeName                       string
	EntityType                      CompanyEntityType
	TaxNumber                       pgtype.Text
	TaxOffice                       pgtype.Text
	BaseCurrency                    string
	Timezone                        string
	IsActive                        bool
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	Version                         int64
	DuplicatePartyTaxNumberPolicy   DuplicateTaxNumberPolicy
	PartyCodePrefix                 string
	PartyCodeDigits                 int16
	FinanceNegativeBalancePolicy    string
	Logo                            string
	HrDefaultContributionSchemeCode pgtype.Text
	// Disposable demo company: may be purged and reseeded by the demo tooling. Always false in a normal installation.
	IsDemo bool
}

type CompanyBusinessSequence struct {
	CompanyID    pgtype.UUID
	SequenceKey  string
	SequenceYear int32
	NextValue    int64
}

type CompanyMembership struct {
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type CompanyModule struct {
	CompanyID  pgtype.UUID
	ModuleCode string
	Enabled    bool
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
	Version    int64
}

type CompanyPartySequence struct {
	CompanyID  pgtype.UUID
	NextNumber int64
}

type CompanyProductSequence struct {
	CompanyID  pgtype.UUID
	Prefix     string
	NextNumber int64
	Digits     int16
	UpdatedAt  pgtype.Timestamptz
}

type CompanySecret struct {
	CompanyID  pgtype.UUID
	Name       string
	Ciphertext []byte
	KeyVersion int16
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CompanySmtpSetting struct {
	CompanyID             pgtype.UUID
	Host                  string
	Port                  int32
	SecurityMode          string
	Username              string
	PasswordCiphertext    []byte
	FromEmail             string
	FromName              string
	ConnectTimeoutSeconds int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int64
}

type DemoState struct {
	Singleton   bool
	Status      string
	LastResetAt pgtype.Timestamptz
	NextResetAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Document struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentTypeCode   string
	DocumentNo         string
	BranchID           pgtype.UUID
	WarehouseID        pgtype.UUID
	PartyID            pgtype.UUID
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	CurrencyCode       string
	ExchangeRate       pgtype.Numeric
	Notes              string
	Status             string
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	GrandTotal         pgtype.Numeric
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	SearchVector       interface{}
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	PostIdempotencyKey pgtype.Text
	PostedBy           pgtype.UUID
}

type DocumentLine struct {
	ID                             pgtype.UUID
	CompanyID                      pgtype.UUID
	DocumentID                     pgtype.UUID
	LineNo                         int32
	ProductID                      pgtype.UUID
	ProductCodeSnapshot            string
	ProductNameSnapshot            string
	UnitCode                       string
	Quantity                       pgtype.Numeric
	UnitPrice                      pgtype.Numeric
	DiscountRate                   pgtype.Numeric
	TaxRate                        pgtype.Numeric
	GrossAmount                    pgtype.Numeric
	DiscountAmount                 pgtype.Numeric
	NetAmount                      pgtype.Numeric
	TaxAmount                      pgtype.Numeric
	LineTotal                      pgtype.Numeric
	CreatedAt                      pgtype.Timestamptz
	TaxTreatment                   string
	TaxDefinitionID                pgtype.UUID
	TaxCodeSnapshot                string
	TaxRateSnapshot                pgtype.Numeric
	TaxIncludedSnapshot            bool
	WithholdingCodeSnapshot        string
	WithholdingRateSnapshot        pgtype.Numeric
	ExemptionCodeSnapshot          string
	TaxNoteSnapshot                string
	ProductTaxProfileVersion       int64
	TaxDefinitionCodeSnapshot      string
	TaxDefinitionNameSnapshot      string
	TaxCalculationTypeSnapshot     string
	WithholdingNumeratorSnapshot   pgtype.Int4
	WithholdingDenominatorSnapshot pgtype.Int4
	ExemptionReasonSnapshot        string
	TaxBaseSnapshot                pgtype.Numeric
	TaxAmountSnapshot              pgtype.Numeric
	TaxComponentsSnapshot          []byte
	VariantID                      pgtype.UUID
	VariantCodeSnapshot            string
	VariantAttributesSnapshot      []byte
	WithholdingAmountSnapshot      pgtype.Numeric
	PayableAmountSnapshot          pgtype.Numeric
}

type DocumentReversal struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	OriginalDocumentID pgtype.UUID
	ReversalDocumentID pgtype.UUID
	FinanceReversalID  pgtype.UUID
	Reason             string
	ActorUserID        pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	IdempotencyKey     pgtype.Text
}

type DocumentSequence struct {
	CompanyID        pgtype.UUID
	DocumentTypeCode string
	NextNumber       int64
	UpdatedAt        pgtype.Timestamptz
}

type DocumentStatusHistory struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	DocumentID  pgtype.UUID
	FromStatus  pgtype.Text
	ToStatus    string
	ActorUserID pgtype.UUID
	Reason      string
	OccurredAt  pgtype.Timestamptz
}

type DocumentType struct {
	Code          string
	CompanyID     pgtype.UUID
	DisplayName   string
	Direction     string
	Kind          string
	StockEffect   string
	FinanceEffect string
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
}

type Edocument struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	ProviderKey        string
	Status             string
	Version            int64
	Payload            []byte
	ProviderExternalID pgtype.Text
	ProviderResult     []byte
	CreatedByUserID    pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type EdocumentEvent struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	EdocumentID        pgtype.UUID
	EventType          string
	Status             string
	ProviderExternalID pgtype.Text
	Message            string
	ActorUserID        pgtype.UUID
	TraceID            pgtype.Text
	OccurredAt         pgtype.Timestamptz
}

type EmailMessage struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	ContextType  string
	ContextID    string
	TemplateID   pgtype.UUID
	Subject      string
	Body         string
	Status       string
	SentCount    int32
	FailedCount  int32
	SkippedCount int32
	RequestedBy  pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type EmailMessageRecipient struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	MessageID        pgtype.UUID
	Recipient        string
	RecipientName    string
	Status           string
	SmtpResponseCode pgtype.Int4
	ErrorCode        pgtype.Text
	SentAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type EmailTemplate struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	Code        string
	Name        string
	Scope       string
	Subject     string
	Body        string
	Description string
	IsSystem    bool
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type Employee struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	EmployeeCode   string
	FirstName      string
	LastName       string
	Status         string
	PositionTitle  string
	WorkEmail      pgtype.Text
	PersonalEmail  pgtype.Text
	Phone          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
	OccupationCode pgtype.Text
}

type EmployeeAddress struct {
	CompanyID      pgtype.UUID
	EmployeeID     pgtype.UUID
	AddressLine    string
	PostalCode     pgtype.Text
	ProvinceID     pgtype.Int2
	DistrictID     pgtype.Int8
	NeighborhoodID pgtype.Int8
	Neighborhood   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
}

type EmployeeAdvance struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	EmployeeID            pgtype.UUID
	AccountID             pgtype.UUID
	OriginalAmount        pgtype.Numeric
	Currency              string
	AdvanceDate           pgtype.Date
	ExpectedRepaymentDate pgtype.Date
	Description           string
	Reference             string
	CreatedBy             pgtype.UUID
	CreatedAt             pgtype.Timestamptz
}

type EmployeeAdvanceTransaction struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	AdvanceID         pgtype.UUID
	TransactionType   string
	Amount            pgtype.Numeric
	TransactionDate   pgtype.Date
	AccountID         pgtype.UUID
	FinanceMovementID pgtype.UUID
	ReversalOfID      pgtype.UUID
	Reason            string
	Description       string
	IdempotencyKey    string
	PayloadHash       string
	ActorUserID       pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

type EmployeeDocument struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	EmployeeID       pgtype.UUID
	DocumentType     string
	Sensitivity      string
	StorageKey       string
	Sha256           string
	MimeType         string
	SizeBytes        int64
	ArchivedAt       pgtype.Timestamptz
	ArchivedBy       pgtype.UUID
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	OriginalFilename string
}

type EmployeeLegalDeduction struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	EmployeeID    pgtype.UUID
	DeductionType string
	Reference     string
	Amount        pgtype.Numeric
	Status        string
	CreatedAt     pgtype.Timestamptz
}

type EmployeePayroll struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	GenerationID          pgtype.UUID
	PayrollRunID          pgtype.UUID
	EmployeeID            pgtype.UUID
	Status                string
	Gross                 pgtype.Numeric
	SgkBase               pgtype.Numeric
	EmployeeSgk           pgtype.Numeric
	EmployeeUnemployment  pgtype.Numeric
	IncomeTaxBase         pgtype.Numeric
	IncomeTax             pgtype.Numeric
	StampTax              pgtype.Numeric
	TotalDeductions       pgtype.Numeric
	Net                   pgtype.Numeric
	EmployerContributions pgtype.Numeric
	EmployerCost          pgtype.Numeric
	PaidDays              pgtype.Numeric
	SgkDays               pgtype.Int2
	EmployeeInputChecksum string
	EmployeeSnapshot      []byte
	CompanySnapshot       []byte
	LegislationSnapshot   []byte
	AttendanceSnapshot    []byte
	ErrorDetails          []byte
	CreatedAt             pgtype.Timestamptz
}

type EmployeePayrollComponent struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	EmployeePayrollID pgtype.UUID
	ComponentCode     string
	ComponentName     string
	ComponentKind     string
	Amount            pgtype.Numeric
	CalculationOrder  int32
	Metadata          []byte
}

type EmployeePayrollYearOpening struct {
	ID                      pgtype.UUID
	CompanyID               pgtype.UUID
	EmployeeID              pgtype.UUID
	TaxYear                 int32
	Source                  string
	CumulativeIncomeTaxBase pgtype.Numeric
	EvidenceNote            string
	CreatedBy               pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	Version                 int64
}

type EmployeePrivateProfile struct {
	CompanyID             pgtype.UUID
	EmployeeID            pgtype.UUID
	TcknCiphertext        []byte
	TcknSha256            []byte
	IbanCiphertext        []byte
	BirthDate             pgtype.Date
	EmergencyContactName  pgtype.Text
	EmergencyContactPhone pgtype.Text
	PayrollEmail          pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int64
	BankName              pgtype.Text
}

type EmployeeScheduleAssignment struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	EmployeeID    pgtype.UUID
	TemplateID    pgtype.UUID
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	CreatedAt     pgtype.Timestamptz
	Version       int64
}

type Employment struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	EmployeeID        pgtype.UUID
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	TerminationReason pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
}

type EmploymentTerm struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	EmploymentID           pgtype.UUID
	EmployeeID             pgtype.UUID
	EffectiveFrom          pgtype.Date
	EffectiveTo            pgtype.Date
	WageType               string
	WagePeriod             string
	GrossWage              pgtype.Numeric
	Currency               string
	WorkType               string
	WeeklyMinutes          int32
	ContributionSchemeCode string
	PriorEmployerTaxPolicy string
	CreatedAt              pgtype.Timestamptz
	Version                int64
	SgkStatus              string
	IsMinimumWage          bool
}

type ExchangeRate struct {
	CompanyID    pgtype.UUID
	CurrencyCode string
	RateDate     pgtype.Date
	RateToBase   pgtype.Numeric
	SourceCode   string
	SourceUrl    string
	FetchedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ExchangeRateSetting struct {
	CompanyID            pgtype.UUID
	SourcePreference     string
	RefreshIntervalHours int16
	LastAttemptAt        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastRateDate         pgtype.Date
	LastSource           pgtype.Text
	LastError            string
	UpdatedAt            pgtype.Timestamptz
	Version              int64
}

type ExportArtifact struct {
	CompanyID   pgtype.UUID
	ExportJobID pgtype.UUID
	StorageKey  string
	Sha256      string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}

type ExportJob struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	EntityType         string
	Format             string
	Status             string
	ArtifactStorageKey pgtype.Text
	Filename           pgtype.Text
	ContentType        pgtype.Text
	RowCount           int32
	ErrorMessage       string
	RequestedBy        pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}

type FinanceAccount struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	AccountType    string
	Code           string
	Name           string
	Currency       string
	BranchID       pgtype.UUID
	BankName       string
	Iban           string
	AccountNumber  string
	Description    string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
	BankBranchName string
	BankBranchCode string
	Notes          string
}

type FinanceAccountMovement struct {
	ID                   pgtype.UUID
	CompanyID            pgtype.UUID
	AccountID            pgtype.UUID
	MovementKind         string
	Direction            string
	Currency             string
	Amount               pgtype.Numeric
	TransactionDate      pgtype.Date
	SourceType           string
	SourceID             pgtype.UUID
	IdempotencyKey       string
	Description          string
	ReversalOfID         pgtype.UUID
	ActorUserID          pgtype.UUID
	Snapshot             []byte
	PostedAt             pgtype.Timestamptz
	ExchangeRate         pgtype.Numeric
	BaseCurrency         pgtype.Text
	BaseAmount           pgtype.Numeric
	ExternalReference    string
	BankStatementLineID  pgtype.Text
	ReconciliationStatus pgtype.Text
	DocumentNo           string
}

type FinanceInstrument struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	InstrumentType string
	InstrumentNo   string
	PartyID        pgtype.UUID
	Currency       string
	Amount         pgtype.Numeric
	IssueDate      pgtype.Date
	DueDate        pgtype.Date
	BankName       string
	DrawerName     string
	Description    string
	Status         string
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type FinanceInstrumentEvent struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	InstrumentID pgtype.UUID
	EventType    string
	EventDate    pgtype.Date
	Description  string
	SourceType   string
	SourceID     pgtype.UUID
	ActorUserID  pgtype.UUID
	OccurredAt   pgtype.Timestamptz
}

type FinanceInvoiceOpenItem struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	PartyID            pgtype.UUID
	PartyLedgerEntryID pgtype.UUID
	Side               string
	Currency           string
	OriginalAmount     pgtype.Numeric
	ExchangeRate       pgtype.Numeric
	BaseCurrency       string
	BaseAmount         pgtype.Numeric
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	CreatedAt          pgtype.Timestamptz
}

type FinanceInvoiceOpenItemReversal struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	OpenItemID            pgtype.UUID
	DocumentID            pgtype.UUID
	ReversalLedgerEntryID pgtype.UUID
	Amount                pgtype.Numeric
	CreatedAt             pgtype.Timestamptz
}

type FinanceInvoicePosting struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	PartyLedgerEntryID pgtype.UUID
	OpenItemID         pgtype.UUID
	IdempotencyKey     string
	PostedBy           pgtype.UUID
	PostedAt           pgtype.Timestamptz
}

type FinanceInvoiceReturnAttribution struct {
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	ReturnDocumentID   pgtype.UUID
	ReturnDocumentDate pgtype.Date
	Amount             pgtype.Numeric
}

type FinanceManualEntry struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	PartyID            pgtype.UUID
	PartyLedgerEntryID pgtype.UUID
	EntryKind          string
	Currency           string
	Amount             pgtype.Numeric
	ExchangeRate       pgtype.Numeric
	BaseCurrency       pgtype.Text
	BaseAmount         pgtype.Numeric
	Description        string
	TransactionDate    pgtype.Date
	IdempotencyKey     string
	ReversalOfID       pgtype.UUID
	ActorUserID        pgtype.UUID
	PostedAt           pgtype.Timestamptz
	DocumentNo         string
	ReferenceNo        string
	DueDate            pgtype.Date
}

type FinancePartyTransfer struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	FromPartyID         pgtype.UUID
	ToPartyID           pgtype.UUID
	DebitLedgerEntryID  pgtype.UUID
	CreditLedgerEntryID pgtype.UUID
	Currency            string
	Amount              pgtype.Numeric
	Description         string
	TransactionDate     pgtype.Date
	IdempotencyKey      string
	ReversalOfID        pgtype.UUID
	ActorUserID         pgtype.UUID
	PostedAt            pgtype.Timestamptz
}

type FinancePayment struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	PartyID            pgtype.UUID
	AccountID          pgtype.UUID
	MovementID         pgtype.UUID
	PartyLedgerEntryID pgtype.UUID
	PaymentKind        string
	MovementDirection  string
	Currency           string
	Amount             pgtype.Numeric
	DocumentNo         string
	Description        string
	TransactionDate    pgtype.Date
	IdempotencyKey     string
	ReversalOfID       pgtype.UUID
	ActorUserID        pgtype.UUID
	Snapshot           []byte
	PostedAt           pgtype.Timestamptz
	PaymentMethod      string
	ExchangeRate       pgtype.Numeric
	BaseCurrency       pgtype.Text
	BaseAmount         pgtype.Numeric
	InstrumentID       pgtype.UUID
	ReferenceNo        string
}

type FinancePaymentAllocation struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	PaymentID      pgtype.UUID
	PartyID        pgtype.UUID
	TargetType     string
	TargetID       pgtype.UUID
	Currency       string
	Amount         pgtype.Numeric
	IdempotencyKey string
	ReversalOfID   pgtype.UUID
	ActorUserID    pgtype.UUID
	Snapshot       []byte
	AllocatedAt    pgtype.Timestamptz
	OpenItemID     pgtype.UUID
}

type FinancePeriodLock struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Reason      string
	LockedBy    pgtype.UUID
	LockedAt    pgtype.Timestamptz
}

type FinanceTransfer struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	FromAccountID     pgtype.UUID
	ToAccountID       pgtype.UUID
	OutMovementID     pgtype.UUID
	InMovementID      pgtype.UUID
	Currency          string
	Amount            pgtype.Numeric
	DocumentNo        string
	ExternalReference string
	Description       string
	TransactionDate   pgtype.Date
	IdempotencyKey    string
	ReversalOfID      pgtype.UUID
	ActorUserID       pgtype.UUID
	Snapshot          []byte
	PostedAt          pgtype.Timestamptz
}

type FixedAsset struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	AssetCode    string
	Name         string
	Category     string
	SerialNumber pgtype.Text
	Description  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}

type FixedAssetCategory struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	Code        string
	Name        string
	Description string
	IsSystem    bool
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type GoodsReceipt struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	ReceiptNo           string
	PurchaseOrderID     pgtype.UUID
	SupplierID          pgtype.UUID
	BranchID            pgtype.UUID
	WarehouseID         pgtype.UUID
	ReceiptDate         pgtype.Date
	Status              string
	OverDeliveryWarning bool
	Notes               string
	CreatedBy           pgtype.UUID
	PostedAt            pgtype.Timestamptz
	DocumentID          pgtype.UUID
	Currency            string
	Version             int64
	CancelledAt         pgtype.Timestamptz
	CancellationReason  pgtype.Text
	CreatedAt           pgtype.Timestamptz
}

type GoodsReceiptLine struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	ReceiptID           pgtype.UUID
	PurchaseOrderLineID pgtype.UUID
	LineNo              int32
	ProductID           pgtype.UUID
	VariantID           pgtype.UUID
	AcceptedQuantity    pgtype.Numeric
	DamagedQuantity     pgtype.Numeric
	RejectedQuantity    pgtype.Numeric
	UnitCode            string
	UnitCost            pgtype.Numeric
	Currency            string
	LotSnapshot         []byte
	SerialSnapshot      []byte
	TaxSnapshot         []byte
	ConversionFactor    pgtype.Numeric
	BaseQuantity        pgtype.Numeric
	WarehouseID         pgtype.UUID
}

type ImportJob struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	EntityType        string
	Direction         string
	TargetID          pgtype.UUID
	Status            string
	CommitMode        string
	DryRun            bool
	SourceFilename    string
	SourceContentType string
	SourceStorageKey  string
	SourceSha256      string
	RowCount          int32
	ErrorCount        int32
	WarningCount      int32
	CreatedBy         pgtype.UUID
	CommittedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AnalysisRevision  string
	PreviewHash       string
	CommittingAt      pgtype.Timestamptz
	CommitToken       pgtype.UUID
	LastError         string
}

type ImportMapping struct {
	CompanyID     pgtype.UUID
	ImportJobID   pgtype.UUID
	SourceColumn  string
	TargetField   string
	MappingSource string
	CreatedAt     pgtype.Timestamptz
}

type ImportRowResult struct {
	CompanyID   pgtype.UUID
	ImportJobID pgtype.UUID
	RowNumber   int32
	RowKey      string
	Status      string
	Values      []byte
	Errors      []byte
	Warnings    []byte
	CreatedAt   pgtype.Timestamptz
}

type InstanceSetup struct {
	Singleton   bool
	CompletedAt pgtype.Timestamptz
	CompletedBy pgtype.UUID
}

type InventoryCompanyPolicy struct {
	CompanyID           pgtype.UUID
	NegativeStockPolicy string
	ExpiredLotPolicy    string
	CostMethod          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type InventoryReasonCode struct {
	Code        string
	DisplayName string
	IsActive    bool
}

type LeaveType struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	Code             string
	Name             string
	PayrollTreatment string
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
}

type Location struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	WarehouseID pgtype.UUID
	ParentID    pgtype.UUID
	Code        string
	Name        string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type LoginAttempt struct {
	ID          int64
	EmailHash   []byte
	IpHash      []byte
	Succeeded   bool
	AttemptedAt pgtype.Timestamptz
}

type Lot struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	ProductID         pgtype.UUID
	LotNumber         string
	ManufacturedAt    pgtype.Date
	ExpiresAt         pgtype.Date
	SupplierReference string
	Metadata          []byte
	CreatedAt         pgtype.Timestamptz
}

type MembershipBranchScope struct {
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	BranchID  pgtype.UUID
}

type MembershipFinanceAccountScope struct {
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type MembershipRole struct {
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
}

type MembershipWarehouseScope struct {
	CompanyID   pgtype.UUID
	UserID      pgtype.UUID
	WarehouseID pgtype.UUID
}

type OutboxEvent struct {
	EventID        pgtype.UUID
	Type           string
	SchemaVersion  int32
	CompanyID      pgtype.UUID
	OccurredAt     pgtype.Timestamptz
	TraceID        pgtype.Text
	Payload        []byte
	AvailableAt    pgtype.Timestamptz
	Attempts       int32
	LockedAt       pgtype.Timestamptz
	ProcessedAt    pgtype.Timestamptz
	DeadLetteredAt pgtype.Timestamptz
	LastErrorClass pgtype.Text
}

type Party struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	Code                string
	Kind                PartyKind
	IsCustomer          bool
	IsSupplier          bool
	DisplayName         string
	LegalName           pgtype.Text
	TradeName           pgtype.Text
	FirstName           pgtype.Text
	LastName            pgtype.Text
	TaxNumber           pgtype.Text
	IdentityNumber      pgtype.Text
	TaxOffice           pgtype.Text
	DefaultCurrency     string
	PaymentTermID       pgtype.UUID
	PriceListID         pgtype.UUID
	DefaultDiscountRate pgtype.Numeric
	SalesRepUserID      pgtype.UUID
	CreditLimit         pgtype.Numeric
	RiskLimit           pgtype.Numeric
	RiskPolicy          PartyRiskPolicy
	IsActive            bool
	DeactivatedAt       pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
	TaxOfficeID         pgtype.UUID
}

type PartyAddress struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	PartyID        pgtype.UUID
	AddressLine    pgtype.Text
	District       pgtype.Text
	City           string
	IsDefault      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
	Neighborhood   pgtype.Text
	ProvinceID     pgtype.Int2
	DistrictID     pgtype.Int8
	NeighborhoodID pgtype.Int8
}

type PartyContact struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	PartyID    pgtype.UUID
	FullName   string
	Title      pgtype.Text
	Department pgtype.Text
	Email      pgtype.Text
	Phone      pgtype.Text
	IsPrimary  bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Version    int64
}

type PartyCustomFieldDefinition struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	Code          string
	Name          string
	FieldType     CustomFieldType
	SelectOptions []byte
	IsRequired    bool
	IsActive      bool
}

type PartyCustomFieldValue struct {
	CompanyID    pgtype.UUID
	PartyID      pgtype.UUID
	DefinitionID pgtype.UUID
	TextValue    pgtype.Text
	NumberValue  pgtype.Numeric
	DateValue    pgtype.Date
	BooleanValue pgtype.Bool
	SelectValue  pgtype.Text
}

type PartyGroup struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type PartyGroupMembership struct {
	CompanyID pgtype.UUID
	PartyID   pgtype.UUID
	GroupID   pgtype.UUID
}

type PartyLedgerBalanceEffect struct {
	CompanyID        pgtype.UUID
	ID               pgtype.UUID
	PartyID          pgtype.UUID
	Currency         string
	EntryType        string
	SourceType       string
	SourceID         pgtype.UUID
	Description      string
	Debit            pgtype.Numeric
	Credit           pgtype.Numeric
	ExchangeRate     pgtype.Numeric
	BaseAmount       pgtype.Numeric
	SignedAmount     int32
	BaseSignedAmount interface{}
	BaseCurrency     string
	DocumentDate     pgtype.Date
	PostedAt         pgtype.Timestamptz
	ReversalOfID     pgtype.UUID
	ActorUserID      pgtype.UUID
	Snapshot         []byte
}

type PartyLedgerEntry struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	PartyID        pgtype.UUID
	Currency       string
	EntryType      string
	SourceType     string
	SourceID       pgtype.UUID
	IdempotencyKey string
	Description    string
	Debit          pgtype.Numeric
	Credit         pgtype.Numeric
	ExchangeRate   pgtype.Numeric
	DocumentDate   pgtype.Date
	PostedAt       pgtype.Timestamptz
	ReversalOfID   pgtype.UUID
	ActorUserID    pgtype.UUID
	Snapshot       []byte
	CreatedAt      pgtype.Timestamptz
	BaseCurrency   pgtype.Text
	BaseAmount     pgtype.Numeric
}

type PartySearchDocument struct {
	CompanyID     pgtype.UUID
	PartyID       pgtype.UUID
	SearchText    string
	BalanceSearch string
	SearchVector  interface{}
}

type PartyTag struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Name      string
	Color     pgtype.Text
}

type PartyTagAssignment struct {
	CompanyID pgtype.UUID
	PartyID   pgtype.UUID
	TagID     pgtype.UUID
}

type PaymentTerm struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	DueDays   int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type PayrollCalculationGeneration struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	PayrollRunID           pgtype.UUID
	GenerationNo           int32
	Status                 string
	EngineVersion          string
	LegislationPackVersion int32
	PopulationHash         string
	TimesheetChecksum      string
	ManualInputVersion     int64
	InputChecksum          string
	ErrorSummary           []byte
	StartedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
}

type PayrollCalculationJob struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	PayrollRunID      pgtype.UUID
	GenerationID      pgtype.UUID
	Status            string
	ProgressTotal     int32
	ProgressCompleted int32
	CreatedAt         pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
}

type PayrollComponentDefinition struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	PackID        pgtype.UUID
	Code          string
	Name          string
	Ownership     string
	ComponentKind string
	PaymentForm   string
	IsActive      bool
}

type PayrollComponentTreatment struct {
	CompanyID             pgtype.UUID
	ComponentDefinitionID pgtype.UUID
	Levy                  string
	Treatment             string
	LimitValue            pgtype.Numeric
	Qualification         []byte
}

type PayrollContributionScheme struct {
	ID                       pgtype.UUID
	CompanyID                pgtype.UUID
	PackID                   pgtype.UUID
	Code                     string
	Name                     string
	EmployeeSgkRate          pgtype.Numeric
	EmployeeUnemploymentRate pgtype.Numeric
	EmployerSgkRate          pgtype.Numeric
	EmployerUnemploymentRate pgtype.Numeric
	SgdpEmployeeRate         pgtype.Numeric
	SgdpEmployerRate         pgtype.Numeric
}

type PayrollEmailBatch struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	PayrollRunID   pgtype.UUID
	IdempotencyKey string
	Status         string
	IsResend       bool
	RequestedBy    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type PayrollEmailDelivery struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	BatchID           pgtype.UUID
	EmployeePayrollID pgtype.UUID
	PayslipID         pgtype.UUID
	RecipientSnapshot string
	SubjectSnapshot   string
	Status            string
	AttemptCount      int32
	NextAttemptAt     pgtype.Timestamptz
	SmtpResponseCode  pgtype.Int4
	ErrorCode         pgtype.Text
	SentAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type PayrollExportJob struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	PayrollRunID pgtype.UUID
	GenerationID pgtype.UUID
	ExportType   string
	Status       string
	StorageKey   pgtype.Text
	Sha256       pgtype.Text
	SizeBytes    pgtype.Int8
	ErrorCode    pgtype.Text
	RequestedBy  pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type PayrollExportPayslip struct {
	CompanyID         pgtype.UUID
	ExportJobID       pgtype.UUID
	PayslipID         pgtype.UUID
	EmployeePayrollID pgtype.UUID
	DocumentOrder     int32
}

type PayrollIncomeTaxBracket struct {
	CompanyID   pgtype.UUID
	PackID      pgtype.UUID
	CountryCode string
	Sequence    int16
	UpperBound  pgtype.Numeric
	Rate        pgtype.Numeric
}

type PayrollLegislationPack struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	CountryCode         string
	Code                string
	Version             int32
	Status              string
	EffectiveFrom       pgtype.Date
	EffectiveTo         pgtype.Date
	SupersedesPackID    pgtype.UUID
	ChangeReason        pgtype.Text
	MinimumMonthlyGross pgtype.Numeric
	SgkDailyFloor       pgtype.Numeric
	SgkDailyCeiling     pgtype.Numeric
	StampTaxRate        pgtype.Numeric
	SourceMetadata      []byte
	ActivatedAt         pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

type PayrollManualComponent struct {
	ID                    pgtype.UUID
	CompanyID             pgtype.UUID
	PayrollRunID          pgtype.UUID
	EmployeeID            pgtype.UUID
	ComponentDefinitionID pgtype.UUID
	Amount                pgtype.Numeric
	Explanation           string
	ArchivedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int64
}

type PayrollPayment struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	PayrollRunID       pgtype.UUID
	AccountID          pgtype.UUID
	Amount             pgtype.Numeric
	Currency           string
	PaymentDate        pgtype.Date
	Status             string
	Description        string
	FinanceMovementID  pgtype.UUID
	ReversalMovementID pgtype.UUID
	ReversedAt         pgtype.Timestamptz
	ReversedBy         pgtype.UUID
	ReversalReason     pgtype.Text
	IdempotencyKey     string
	CreatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type PayrollPayslip struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	EmployeePayrollID pgtype.UUID
	TemplateVersion   string
	SourceChecksum    string
	StorageKey        string
	Sha256            string
	SizeBytes         int64
	RenderMetadata    []byte
	CreatedAt         pgtype.Timestamptz
}

type PayrollPayslipJob struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	EmployeePayrollID pgtype.UUID
	TemplateVersion   string
	Status            string
	PayslipID         pgtype.UUID
	ErrorCode         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
}

type PayrollRun struct {
	ID                      pgtype.UUID
	CompanyID               pgtype.UUID
	RunNumber               string
	RunType                 string
	CorrectionOfRunID       pgtype.UUID
	PeriodYear              int32
	PeriodMonth             int16
	PaymentDate             pgtype.Date
	TimesheetPeriodID       pgtype.UUID
	LegislationPackID       pgtype.UUID
	Status                  string
	ActiveGenerationID      pgtype.UUID
	TotalGross              pgtype.Numeric
	TotalEmployeeDeductions pgtype.Numeric
	TotalNet                pgtype.Numeric
	TotalEmployerCost       pgtype.Numeric
	FinalizedAt             pgtype.Timestamptz
	FinalizedBy             pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Version                 int64
}

type Permission struct {
	Code        string
	Description string
}

// Varya One runtime metadata; business settings belong to their owning domain.
type PlatformMetadatum struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type PriceList struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	Code                   string
	Name                   string
	CurrencyCode           string
	TaxMode                string
	RoundPolicy            string
	RoundScale             int16
	IsActive               bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
	Description            string
	AppliesToAllCategories bool
	ScopeCategoryID        pgtype.UUID
}

type PriceListEntry struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	PriceListID pgtype.UUID
	ItemID      pgtype.UUID
	ValidFrom   pgtype.Date
	ValidTo     pgtype.Date
	UnitPrice   pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
	VariantID   pgtype.UUID
}

type PricingCurrency struct {
	CompanyID pgtype.UUID
	Code      string
	Name      string
	Symbol    string
	MinorUnit int16
	IsCustom  bool
	Source    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type Product struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	Code                string
	Name                string
	Kind                ProductKind
	Description         string
	CategoryID          pgtype.UUID
	BrandID             pgtype.UUID
	IsActive            bool
	SearchVector        interface{}
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
	PurchasePrice       pgtype.Numeric
	SalesPrice          pgtype.Numeric
	CustomDescription1  string
	CustomDescription2  string
	CustomDescription3  string
	PurchaseTaxType     string
	SalesTaxType        string
	PurchaseTaxRate     pgtype.Numeric
	SalesTaxRate        pgtype.Numeric
	PurchaseTaxIncluded bool
	SalesTaxIncluded    bool
	ExciseTaxRate       pgtype.Numeric
	WithholdingCode     string
	WithholdingRate     pgtype.Numeric
	ExemptionCode       string
	TaxNote             string
	VariantsEnabled     bool
}

type ProductAttachment struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	ProductID        pgtype.UUID
	VariantID        pgtype.UUID
	AttachmentKind   string
	StorageKey       string
	OriginalFilename string
	ContentType      string
	ByteSize         int64
	Sha256           string
	Description      string
	UploadedBy       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	ArchivedAt       pgtype.Timestamptz
	Version          int64
}

type ProductBarcode struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	ProductID   pgtype.UUID
	Barcode     string
	BarcodeType string
	IsPrimary   bool
	CreatedAt   pgtype.Timestamptz
	VariantID   pgtype.UUID
}

type ProductBrand struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type ProductCategory struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type ProductImage struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	ProductID           pgtype.UUID
	VariantID           pgtype.UUID
	SourceStorageKey    string
	MasterStorageKey    string
	OriginalFilename    string
	OriginalContentType string
	OriginalSize        int64
	MasterSize          int64
	Width               int32
	Height              int32
	Orientation         int16
	Sha256              string
	MasterSha256        string
	Position            int32
	IsPrimary           bool
	ArchivedAt          pgtype.Timestamptz
	UploadedBy          pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
}

type ProductImageVariant struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	ProductImageID pgtype.UUID
	VariantCode    string
	StorageKey     string
	ContentType    string
	ByteSize       int64
	Width          int32
	Height         int32
	Sha256         string
	GeneratedAt    pgtype.Timestamptz
}

type ProductTaxProfile struct {
	CompanyID              pgtype.UUID
	ProductID              pgtype.UUID
	Direction              string
	Treatment              string
	TaxDefinitionID        pgtype.UUID
	TaxRateID              pgtype.UUID
	TaxCode                string
	Rate                   pgtype.Numeric
	TaxIncluded            bool
	WithholdingRuleID      pgtype.UUID
	WithholdingCode        string
	WithholdingRate        pgtype.Numeric
	ExemptionID            pgtype.UUID
	ExemptionCode          string
	TaxNote                string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
	WithholdingNumerator   pgtype.Int2
	WithholdingDenominator pgtype.Int2
}

type ProductTaxProfileComponent struct {
	CompanyID         pgtype.UUID
	ProductID         pgtype.UUID
	Direction         string
	Sequence          int16
	TaxDefinitionID   pgtype.UUID
	TaxRateID         pgtype.UUID
	CalculationType   string
	IncludedInTaxBase bool
	Metadata          []byte
}

type ProductUnit struct {
	CompanyID        pgtype.UUID
	ProductID        pgtype.UUID
	UnitCode         string
	IsBase           bool
	ConversionFactor pgtype.Numeric
	DecimalScale     int16
}

type ProductVariant struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	ProductID        pgtype.UUID
	VariantCode      string
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	VariantSignature string
}

type ProductVariantAllowedOption struct {
	CompanyID    pgtype.UUID
	ProductID    pgtype.UUID
	DefinitionID pgtype.UUID
	OptionID     pgtype.UUID
}

type ProductVariantDefinition struct {
	CompanyID    pgtype.UUID
	ProductID    pgtype.UUID
	DefinitionID pgtype.UUID
	Position     int16
}

type ProductVariantPriceOverride struct {
	CompanyID pgtype.UUID
	VariantID pgtype.UUID
	Direction string
	UnitPrice pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProductVariantValue struct {
	CompanyID    pgtype.UUID
	VariantID    pgtype.UUID
	DefinitionID pgtype.UUID
	OptionID     pgtype.UUID
}

type PublicHoliday struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	CalendarID   pgtype.UUID
	CalendarYear int32
	HolidayDate  pgtype.Date
	Name         string
	Duration     string
}

type PublicHolidayCalendar struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	CountryCode  string
	CalendarYear int32
	Version      int32
	Status       string
	SourceName   string
	SourceUrl    string
	PublishedOn  pgtype.Date
	CreatedAt    pgtype.Timestamptz
	ActivatedAt  pgtype.Timestamptz
}

type PurchaseInvoice struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	InvoiceNo          string
	SupplierID         pgtype.UUID
	BranchID           pgtype.UUID
	PurchaseOrderID    pgtype.UUID
	GoodsReceiptID     pgtype.UUID
	InvoiceDate        pgtype.Date
	DueDate            pgtype.Date
	Currency           string
	Status             string
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	PayableTotal       pgtype.Numeric
	TaxSnapshot        []byte
	FinancePostingID   pgtype.UUID
	CreatedBy          pgtype.UUID
	PostedAt           pgtype.Timestamptz
	DocumentID         pgtype.UUID
	WarehouseID        pgtype.UUID
	Version            int64
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

type PurchaseInvoiceLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	InvoiceID                  pgtype.UUID
	GoodsReceiptLineID         pgtype.UUID
	LineNo                     int32
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	DescriptionSnapshot        string
	Quantity                   pgtype.Numeric
	UnitPrice                  pgtype.Numeric
	GrossAmount                pgtype.Numeric
	DiscountAmount             pgtype.Numeric
	TaxBase                    pgtype.Numeric
	TaxAmount                  pgtype.Numeric
	WithholdingAmount          pgtype.Numeric
	PayableAmount              pgtype.Numeric
	TaxComponentsSnapshot      []byte
	PurchaseOrderLineID        pgtype.UUID
	WarehouseID                pgtype.UUID
	UnitCode                   string
	ConversionFactor           pgtype.Numeric
	BaseQuantity               pgtype.Numeric
	LineType                   string
	DiscountComponentsSnapshot []byte
}

type PurchaseLandedCost struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentNo         string
	GoodsReceiptID     pgtype.UUID
	SupplierID         pgtype.UUID
	Description        string
	Amount             pgtype.Numeric
	Currency           string
	ExchangeRate       pgtype.Numeric
	AllocationMethod   string
	Status             string
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
}

type PurchaseLandedCostLine struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	LandedCostID        pgtype.UUID
	GoodsReceiptLineID  pgtype.UUID
	AllocatedAmount     pgtype.Numeric
	BaseAllocatedAmount pgtype.Numeric
	BaseCurrency        pgtype.Text
}

type PurchaseOrder struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	OrderNo            string
	SupplierID         pgtype.UUID
	BranchID           pgtype.UUID
	WarehouseID        pgtype.UUID
	OrderDate          pgtype.Date
	Currency           string
	Status             string
	OverDeliveryPolicy string
	Notes              string
	Total              pgtype.Numeric
	ConfirmedAt        pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	DocumentID         pgtype.UUID
	DiscountTotal      pgtype.Numeric
}

type PurchaseOrderLine struct {
	ID                          pgtype.UUID
	CompanyID                   pgtype.UUID
	OrderID                     pgtype.UUID
	LineNo                      int32
	ProductID                   pgtype.UUID
	VariantID                   pgtype.UUID
	SupplierProductCodeSnapshot string
	ProductCodeSnapshot         string
	ProductNameSnapshot         string
	UnitCode                    string
	OrderedQuantity             pgtype.Numeric
	ReceivedQuantity            pgtype.Numeric
	InvoicedQuantity            pgtype.Numeric
	UnitPrice                   pgtype.Numeric
	Currency                    string
	TaxSnapshot                 []byte
	CreatedAt                   pgtype.Timestamptz
	WarehouseID                 pgtype.UUID
	ConversionFactor            pgtype.Numeric
	BaseQuantity                pgtype.Numeric
	LineType                    string
	DiscountAmount              pgtype.Numeric
	DiscountComponentsSnapshot  []byte
	NetAmount                   pgtype.Numeric
}

type PurchaseReturn struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	ReturnNo           string
	SupplierID         pgtype.UUID
	BranchID           pgtype.UUID
	WarehouseID        pgtype.UUID
	SourceReceiptID    pgtype.UUID
	ReturnDate         pgtype.Date
	Currency           string
	Status             string
	Total              pgtype.Numeric
	Reason             string
	FinancePostingID   pgtype.UUID
	CreatedBy          pgtype.UUID
	PostedAt           pgtype.Timestamptz
	DocumentID         pgtype.UUID
	Version            int64
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

type PurchaseReturnLine struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	ReturnID            pgtype.UUID
	SourceReceiptLineID pgtype.UUID
	LineNo              int32
	ProductID           pgtype.UUID
	VariantID           pgtype.UUID
	Quantity            pgtype.Numeric
	UnitCode            string
	UnitCost            pgtype.Numeric
	Currency            string
	Reason              string
	ConversionFactor    pgtype.Numeric
	BaseQuantity        pgtype.Numeric
	WarehouseID         pgtype.UUID
}

type RecoveryCode struct {
	UserID    pgtype.UUID
	CodeHash  []byte
	CreatedAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Name      string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type RolePermission struct {
	CompanyID      pgtype.UUID
	RoleID         pgtype.UUID
	PermissionCode string
}

type SalesDispatch struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	DocumentNo         string
	BranchID           pgtype.UUID
	DefaultWarehouseID pgtype.UUID
	PartyID            pgtype.UUID
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	ValidUntil         pgtype.Date
	CurrencyCode       string
	ExchangeRate       pgtype.Numeric
	Notes              string
	Status             string
	SourceKind         string
	SourceDocumentID   pgtype.UUID
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	WithholdingTotal   pgtype.Numeric
	GrandTotal         pgtype.Numeric
	PayableTotal       pgtype.Numeric
	FinancePostingID   pgtype.UUID
	PostIdempotencyKey pgtype.Text
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	SalesRepUserID     pgtype.UUID
	PaymentTermID      pgtype.UUID
}

type SalesDispatchLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	DocumentID                 pgtype.UUID
	LineNo                     int32
	LineType                   string
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	WarehouseID                pgtype.UUID
	UnitCode                   string
	Quantity                   pgtype.Numeric
	BaseQuantity               pgtype.Numeric
	ConversionFactor           pgtype.Numeric
	PriceSource                string
	PriceListSnapshot          []byte
	DiscountComponentsSnapshot []byte
	TaxSnapshot                []byte
	DescriptionSnapshot        string
	SourceLineID               pgtype.UUID
	UnitPrice                  pgtype.Numeric
	GrossAmount                pgtype.Numeric
	DiscountAmount             pgtype.Numeric
	NetAmount                  pgtype.Numeric
	TaxAmount                  pgtype.Numeric
	WithholdingAmount          pgtype.Numeric
	LineTotal                  pgtype.Numeric
	PayableAmount              pgtype.Numeric
	CreatedAt                  pgtype.Timestamptz
	VariantCodeSnapshot        string
	VariantAttributesSnapshot  []byte
	TaxComponentsSnapshot      []byte
}

type SalesInvoice struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	DocumentNo         string
	BranchID           pgtype.UUID
	DefaultWarehouseID pgtype.UUID
	PartyID            pgtype.UUID
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	ValidUntil         pgtype.Date
	CurrencyCode       string
	ExchangeRate       pgtype.Numeric
	Notes              string
	Status             string
	SourceKind         string
	SourceDocumentID   pgtype.UUID
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	WithholdingTotal   pgtype.Numeric
	GrandTotal         pgtype.Numeric
	PayableTotal       pgtype.Numeric
	FinancePostingID   pgtype.UUID
	PostIdempotencyKey pgtype.Text
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	SalesRepUserID     pgtype.UUID
	PaymentTermID      pgtype.UUID
}

type SalesInvoiceLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	DocumentID                 pgtype.UUID
	LineNo                     int32
	LineType                   string
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	WarehouseID                pgtype.UUID
	UnitCode                   string
	Quantity                   pgtype.Numeric
	BaseQuantity               pgtype.Numeric
	ConversionFactor           pgtype.Numeric
	PriceSource                string
	PriceListSnapshot          []byte
	DiscountComponentsSnapshot []byte
	TaxSnapshot                []byte
	DescriptionSnapshot        string
	SourceLineID               pgtype.UUID
	UnitPrice                  pgtype.Numeric
	GrossAmount                pgtype.Numeric
	DiscountAmount             pgtype.Numeric
	NetAmount                  pgtype.Numeric
	TaxAmount                  pgtype.Numeric
	WithholdingAmount          pgtype.Numeric
	LineTotal                  pgtype.Numeric
	PayableAmount              pgtype.Numeric
	CreatedAt                  pgtype.Timestamptz
	VariantCodeSnapshot        string
	VariantAttributesSnapshot  []byte
	TaxComponentsSnapshot      []byte
}

type SalesOrder struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	DocumentNo         string
	BranchID           pgtype.UUID
	DefaultWarehouseID pgtype.UUID
	PartyID            pgtype.UUID
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	ValidUntil         pgtype.Date
	CurrencyCode       string
	ExchangeRate       pgtype.Numeric
	Notes              string
	Status             string
	SourceKind         string
	SourceDocumentID   pgtype.UUID
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	WithholdingTotal   pgtype.Numeric
	GrandTotal         pgtype.Numeric
	PayableTotal       pgtype.Numeric
	FinancePostingID   pgtype.UUID
	PostIdempotencyKey pgtype.Text
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	SalesRepUserID     pgtype.UUID
	PaymentTermID      pgtype.UUID
}

type SalesOrderLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	DocumentID                 pgtype.UUID
	LineNo                     int32
	LineType                   string
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	WarehouseID                pgtype.UUID
	UnitCode                   string
	Quantity                   pgtype.Numeric
	BaseQuantity               pgtype.Numeric
	ConversionFactor           pgtype.Numeric
	PriceSource                string
	PriceListSnapshot          []byte
	DiscountComponentsSnapshot []byte
	TaxSnapshot                []byte
	DescriptionSnapshot        string
	SourceLineID               pgtype.UUID
	UnitPrice                  pgtype.Numeric
	GrossAmount                pgtype.Numeric
	DiscountAmount             pgtype.Numeric
	NetAmount                  pgtype.Numeric
	TaxAmount                  pgtype.Numeric
	WithholdingAmount          pgtype.Numeric
	LineTotal                  pgtype.Numeric
	PayableAmount              pgtype.Numeric
	CreatedAt                  pgtype.Timestamptz
	VariantCodeSnapshot        string
	VariantAttributesSnapshot  []byte
	TaxComponentsSnapshot      []byte
}

type SalesOrderReservation struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	OrderID          pgtype.UUID
	OrderLineID      pgtype.UUID
	WarehouseID      pgtype.UUID
	ProductID        pgtype.UUID
	VariantID        pgtype.UUID
	Quantity         pgtype.Numeric
	ConsumedQuantity pgtype.Numeric
	ReleasedQuantity pgtype.Numeric
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type SalesQuote struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	DocumentNo         string
	BranchID           pgtype.UUID
	DefaultWarehouseID pgtype.UUID
	PartyID            pgtype.UUID
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	ValidUntil         pgtype.Date
	CurrencyCode       string
	ExchangeRate       pgtype.Numeric
	Notes              string
	Status             string
	SourceKind         string
	SourceDocumentID   pgtype.UUID
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	WithholdingTotal   pgtype.Numeric
	GrandTotal         pgtype.Numeric
	PayableTotal       pgtype.Numeric
	FinancePostingID   pgtype.UUID
	PostIdempotencyKey pgtype.Text
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	SalesRepUserID     pgtype.UUID
	PaymentTermID      pgtype.UUID
}

type SalesQuoteLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	DocumentID                 pgtype.UUID
	LineNo                     int32
	LineType                   string
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	WarehouseID                pgtype.UUID
	UnitCode                   string
	Quantity                   pgtype.Numeric
	BaseQuantity               pgtype.Numeric
	ConversionFactor           pgtype.Numeric
	PriceSource                string
	PriceListSnapshot          []byte
	DiscountComponentsSnapshot []byte
	TaxSnapshot                []byte
	DescriptionSnapshot        string
	SourceLineID               pgtype.UUID
	UnitPrice                  pgtype.Numeric
	GrossAmount                pgtype.Numeric
	DiscountAmount             pgtype.Numeric
	NetAmount                  pgtype.Numeric
	TaxAmount                  pgtype.Numeric
	WithholdingAmount          pgtype.Numeric
	LineTotal                  pgtype.Numeric
	PayableAmount              pgtype.Numeric
	CreatedAt                  pgtype.Timestamptz
	VariantCodeSnapshot        string
	VariantAttributesSnapshot  []byte
	TaxComponentsSnapshot      []byte
}

type SalesReturn struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	DocumentID         pgtype.UUID
	DocumentNo         string
	BranchID           pgtype.UUID
	DefaultWarehouseID pgtype.UUID
	PartyID            pgtype.UUID
	DocumentDate       pgtype.Date
	DueDate            pgtype.Date
	ValidUntil         pgtype.Date
	CurrencyCode       string
	ExchangeRate       pgtype.Numeric
	Notes              string
	Status             string
	SourceKind         string
	SourceDocumentID   pgtype.UUID
	Subtotal           pgtype.Numeric
	DiscountTotal      pgtype.Numeric
	TaxTotal           pgtype.Numeric
	WithholdingTotal   pgtype.Numeric
	GrandTotal         pgtype.Numeric
	PayableTotal       pgtype.Numeric
	FinancePostingID   pgtype.UUID
	PostIdempotencyKey pgtype.Text
	PostedAt           pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	CancellationReason pgtype.Text
	CreatedBy          pgtype.UUID
	UpdatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
	Reason             string
	SalesRepUserID     pgtype.UUID
	PaymentTermID      pgtype.UUID
}

type SalesReturnLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	DocumentID                 pgtype.UUID
	LineNo                     int32
	LineType                   string
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	WarehouseID                pgtype.UUID
	UnitCode                   string
	Quantity                   pgtype.Numeric
	BaseQuantity               pgtype.Numeric
	ConversionFactor           pgtype.Numeric
	PriceSource                string
	PriceListSnapshot          []byte
	DiscountComponentsSnapshot []byte
	TaxSnapshot                []byte
	DescriptionSnapshot        string
	SourceLineID               pgtype.UUID
	UnitPrice                  pgtype.Numeric
	GrossAmount                pgtype.Numeric
	DiscountAmount             pgtype.Numeric
	NetAmount                  pgtype.Numeric
	TaxAmount                  pgtype.Numeric
	WithholdingAmount          pgtype.Numeric
	LineTotal                  pgtype.Numeric
	PayableAmount              pgtype.Numeric
	CreatedAt                  pgtype.Timestamptz
	VariantCodeSnapshot        string
	VariantAttributesSnapshot  []byte
	TaxComponentsSnapshot      []byte
}

type SecurityAuditEvent struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	ActorUserID pgtype.UUID
	EventType   string
	EntityType  pgtype.Text
	EntityID    pgtype.UUID
	Details     []byte
	TraceID     pgtype.Text
	SourceIp    pgtype.Text
	UserAgent   pgtype.Text
	OccurredAt  pgtype.Timestamptz
}

type SerialNumber struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	ProductID         pgtype.UUID
	SerialNumber      string
	Status            string
	ActiveWarehouseID pgtype.UUID
	ActiveLocationID  pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SerialNumberEvent struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	SerialID        pgtype.UUID
	MovementID      pgtype.UUID
	FromStatus      pgtype.Text
	ToStatus        string
	FromWarehouseID pgtype.UUID
	ToWarehouseID   pgtype.UUID
	OccurredAt      pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	TokenHash        []byte
	CsrfHash         []byte
	UserID           pgtype.UUID
	CurrentCompanyID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	IpHash           []byte
	UserAgent        pgtype.Text
}

type SgkOccupationCode struct {
	Code string
	Name string
}

type StockCostAdjustment struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	LayerID      pgtype.UUID
	ReasonCode   string
	Amount       pgtype.Numeric
	Currency     string
	BaseAmount   pgtype.Numeric
	BaseCurrency pgtype.Text
	SourceType   string
	SourceID     pgtype.UUID
	Note         string
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type StockCostConsumption struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	MovementID   pgtype.UUID
	LayerID      pgtype.UUID
	Quantity     pgtype.Numeric
	UnitCost     pgtype.Numeric
	Currency     string
	ConsumedAt   pgtype.Timestamptz
	BaseUnitCost pgtype.Numeric
	BaseCurrency pgtype.Text
}

type StockCostLayer struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	WarehouseID       pgtype.UUID
	ProductID         pgtype.UUID
	VariantID         pgtype.UUID
	LotID             pgtype.UUID
	SourceMovementID  pgtype.UUID
	Quantity          pgtype.Numeric
	RemainingQuantity pgtype.Numeric
	UnitCost          pgtype.Numeric
	Currency          string
	CreatedAt         pgtype.Timestamptz
	IsProvisional     bool
	BaseUnitCost      pgtype.Numeric
	BaseCurrency      pgtype.Text
}

type StockCostUnpricedEvent struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	EventType  string
	MovementID pgtype.UUID
	LayerID    pgtype.UUID
	Quantity   pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
}

type StockCount struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	WarehouseID        pgtype.UUID
	State              string
	BlindCount         bool
	SnapshotAt         pgtype.Timestamptz
	PostedAt           pgtype.Timestamptz
	PostedBy           pgtype.UUID
	CancelledAt        pgtype.Timestamptz
	CancellationReason string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Version            int64
}

type StockCountEngineAssignment struct {
	ID         pgtype.UUID
	CompanyID  pgtype.UUID
	CountID    pgtype.UUID
	PassID     pgtype.UUID
	UserID     pgtype.UUID
	Status     string
	AssignedAt pgtype.Timestamptz
	ReleasedAt pgtype.Timestamptz
}

type StockCountEngineCommand struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	CountID        pgtype.UUID
	CommandName    string
	IdempotencyKey string
	PayloadHash    []byte
	CompletedAt    pgtype.Timestamptz
	Result         []byte
	ActorUserID    pgtype.UUID
}

type StockCountEngineCount struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	WarehouseID         pgtype.UUID
	State               string
	MovementPolicy      string
	BlindCount          bool
	SnapshotAt          pgtype.Timestamptz
	Version             int64
	StartIdempotencyKey string
	StartPayloadHash    []byte
	PostedAt            pgtype.Timestamptz
	PostedBy            pgtype.UUID
	CancelledAt         pgtype.Timestamptz
	CancellationReason  string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	// FULL counts may discover zero-balance products and variants while counting; PARTIAL counts remain restricted to their initial scopes.
	ScopeMode string
	// Company-scoped human-readable stock count number, for example SAY-000001.
	CountNo string
	// Optional user-entered stock count description, maximum 500 characters.
	Description string
}

type StockCountEngineEvent struct {
	EventSeq         int64
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	CountID          pgtype.UUID
	PassID           pgtype.UUID
	SessionID        pgtype.UUID
	ScopeID          pgtype.UUID
	EventID          string
	EventType        string
	Barcode          string
	Reason           string
	ResolutionStatus string
	Quantity         pgtype.Numeric
	PayloadHash      []byte
	ActorUserID      pgtype.UUID
	OccurredAt       pgtype.Timestamptz
	RecordedAt       pgtype.Timestamptz
}

type StockCountEngineNumberSequence struct {
	CompanyID  pgtype.UUID
	NextNumber int64
}

type StockCountEnginePass struct {
	ID          pgtype.UUID
	CompanyID   pgtype.UUID
	CountID     pgtype.UUID
	PassNo      int32
	Mode        string
	State       string
	CreatedBy   pgtype.UUID
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type StockCountEngineReviewException struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	CountID       pgtype.UUID
	ScopeID       pgtype.UUID
	ExceptionType string
	Status        string
	Details       []byte
	CreatedAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	ResolvedBy    pgtype.UUID
}

type StockCountEngineScope struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	CountID          pgtype.UUID
	LineNo           int32
	ProductID        pgtype.UUID
	VariantID        pgtype.UUID
	WarehouseID      pgtype.UUID
	LocationID       pgtype.UUID
	LotID            pgtype.UUID
	SerialID         pgtype.UUID
	SnapshotQuantity pgtype.Numeric
}

type StockCountEngineSession struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	CountID         pgtype.UUID
	PassID          pgtype.UUID
	UserID          pgtype.UUID
	ClientSessionID string
	OpenedAt        pgtype.Timestamptz
	ClosedAt        pgtype.Timestamptz
	LastEventSeq    pgtype.Int8
}

type StockCountLine struct {
	ID                 pgtype.UUID
	CompanyID          pgtype.UUID
	CountID            pgtype.UUID
	LineNo             int32
	ProductID          pgtype.UUID
	VariantID          pgtype.UUID
	LocationID         pgtype.UUID
	LotID              pgtype.UUID
	SerialID           pgtype.UUID
	SnapshotQuantity   pgtype.Numeric
	CountedQuantity    pgtype.Numeric
	ExpectedQuantity   pgtype.Numeric
	DifferenceQuantity pgtype.Numeric
	CountedAt          pgtype.Timestamptz
}

type StockMovement struct {
	ID                   pgtype.UUID
	CompanyID            pgtype.UUID
	WarehouseID          pgtype.UUID
	LocationID           pgtype.UUID
	ProductID            pgtype.UUID
	VariantID            pgtype.UUID
	LotID                pgtype.UUID
	SerialID             pgtype.UUID
	MovementType         string
	Direction            string
	Quantity             pgtype.Numeric
	QuantityDelta        pgtype.Numeric
	UnitCost             pgtype.Numeric
	Currency             pgtype.Text
	ReasonCode           string
	ReasonDescription    string
	SourceType           string
	SourceID             pgtype.UUID
	SourceLineID         pgtype.UUID
	IdempotencyKey       string
	PayloadHash          []byte
	ReversalOfID         pgtype.UUID
	ExpiryOverride       bool
	ExpiryOverrideReason string
	Metadata             []byte
	ActorUserID          pgtype.UUID
	PostedAt             pgtype.Timestamptz
	TransferID           pgtype.UUID
	TransferLineID       pgtype.UUID
	CountID              pgtype.UUID
	CountLineID          pgtype.UUID
	OperationID          pgtype.UUID
	ExchangeRateSnapshot pgtype.Numeric
}

type StockMovementOperation struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	WarehouseID       pgtype.UUID
	ProductID         pgtype.UUID
	MovementType      string
	Direction         string
	UnitCode          string
	Currency          pgtype.Text
	ReasonCode        string
	ReasonDescription string
	IdempotencyKey    string
	PayloadHash       []byte
	ActorUserID       pgtype.UUID
	PostedAt          pgtype.Timestamptz
}

type StockMovementOperationLine struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	OperationID    pgtype.UUID
	LineNo         int32
	VariantID      pgtype.UUID
	VariantCode    string
	VariantDisplay []byte
	Quantity       pgtype.Numeric
	BaseQuantity   pgtype.Numeric
	UnitCost       pgtype.Numeric
	MovementID     pgtype.UUID
}

type StockPosition struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	WarehouseID       pgtype.UUID
	LocationID        pgtype.UUID
	ProductID         pgtype.UUID
	VariantID         pgtype.UUID
	LotID             pgtype.UUID
	SerialID          pgtype.UUID
	PhysicalQuantity  pgtype.Numeric
	ReservedQuantity  pgtype.Numeric
	AvailableQuantity pgtype.Numeric
	UpdatedAt         pgtype.Timestamptz
}

type SupplierProductReference struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	SupplierID   pgtype.UUID
	ProductID    pgtype.UUID
	VariantID    pgtype.UUID
	SupplierCode string
	Barcode      string
	IsActive     bool
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SupplierPurchasePrice struct {
	ID                  pgtype.UUID
	CompanyID           pgtype.UUID
	SupplierID          pgtype.UUID
	ProductID           pgtype.UUID
	VariantID           pgtype.UUID
	SourceReceiptLineID pgtype.UUID
	Currency            string
	UnitPrice           pgtype.Numeric
	ObservedAt          pgtype.Timestamptz
}

type TaxDefinition struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	Code            string
	Name            string
	Description     string
	Source          string
	SourceReference string
	SourceVersion   string
	Metadata        []byte
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int64
}

type TaxExemption struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	Code            string
	Name            string
	LegalBasis      string
	Source          string
	SourceReference string
	SourceVersion   string
	ValidFrom       pgtype.Date
	ValidTo         pgtype.Date
	Metadata        []byte
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int64
}

type TaxRate struct {
	ID              pgtype.UUID
	CompanyID       pgtype.UUID
	TaxDefinitionID pgtype.UUID
	Rate            pgtype.Numeric
	ValidFrom       pgtype.Date
	ValidTo         pgtype.Date
	Source          string
	SourceReference string
	SourceVersion   string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int64
	CalculationType string
}

type TaxWithholdingRule struct {
	ID               pgtype.UUID
	CompanyID        pgtype.UUID
	Code             string
	Name             string
	Rate             pgtype.Numeric
	LegalBasis       string
	Source           string
	SourceReference  string
	SourceVersion    string
	ValidFrom        pgtype.Date
	ValidTo          pgtype.Date
	Metadata         []byte
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	RatioNumerator   pgtype.Int2
	RatioDenominator pgtype.Int2
}

type TimesheetDay struct {
	ID                   pgtype.UUID
	CompanyID            pgtype.UUID
	PeriodID             pgtype.UUID
	EmployeeID           pgtype.UUID
	WorkDate             pgtype.Date
	Source               string
	ScheduleVersionID    pgtype.UUID
	PlannedMinutes       int32
	WorkedMinutes        int32
	PaidLeaveMinutes     int32
	UnpaidLeaveMinutes   int32
	OvertimeMinutes      int32
	WeekRestMinutes      int32
	PublicHolidayMinutes int32
	AbsenceMinutes       int32
	Explanation          string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Version              int64
	LeaveTypeID          pgtype.UUID
}

type TimesheetPeriod struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	PeriodYear   int32
	PeriodMonth  int16
	Status       string
	Generation   int32
	Checksum     pgtype.Text
	FinalizedAt  pgtype.Timestamptz
	FinalizedBy  pgtype.UUID
	ReopenReason pgtype.Text
	ReopenedAt   pgtype.Timestamptz
	ReopenedBy   pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}

type TurkishDistrict struct {
	ID         int64
	ProvinceID int16
	Name       string
}

type TurkishNeighborhood struct {
	ID         int64
	DistrictID int64
	Name       string
}

type TurkishProvince struct {
	ID        int16
	PlateCode string
	Name      string
}

type TurkishTaxOffice struct {
	ID            pgtype.UUID
	Code          pgtype.Text
	Name          string
	ProvinceID    int16
	DistrictName  string
	OfficeType    string
	IsActive      bool
	SourceVersion string
	SnapshotDate  pgtype.Date
}

type Unit struct {
	Code         string
	Name         string
	DecimalScale int16
	IsActive     bool
}

type User struct {
	ID                    pgtype.UUID
	Email                 string
	DisplayName           string
	PasswordHash          string
	IsActive              bool
	TotpPendingCiphertext []byte
	TotpSecretCiphertext  []byte
	TotpEnabledAt         pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int64
}

type UserAddressPreference struct {
	CompanyID        pgtype.UUID
	UserID           pgtype.UUID
	ProvinceID       pgtype.Int2
	DistrictID       pgtype.Int8
	NeighborhoodID   pgtype.Int8
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	ProvinceName     pgtype.Text
	DistrictName     pgtype.Text
	NeighborhoodName pgtype.Text
}

type UserAgendaEvent struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	UserID        pgtype.UUID
	EventDate     pgtype.Date
	EventTime     string
	Title         string
	RemindMinutes int32
	NotifiedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int64
	CompletedAt   pgtype.Timestamptz
}

type UserDashboardPreference struct {
	CompanyID       pgtype.UUID
	UserID          pgtype.UUID
	PinnedShortcuts []byte
	Version         int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type UserTablePreference struct {
	CompanyID        pgtype.UUID
	UserID           pgtype.UUID
	TableKey         string
	ColumnVisibility []byte
	Version          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type VariantDefinition struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type VariantDefinitionOption struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	DefinitionID pgtype.UUID
	Code         string
	Name         string
	ShortCode    string
	SortOrder    int32
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}

type VariantDefinitionPackage struct {
	Code        string
	Name        string
	Description string
	IsActive    bool
}

type VariantDefinitionPackageDefinition struct {
	PackageCode    string
	DefinitionCode string
	DefinitionName string
	Position       int16
}

type VariantDefinitionPackageOption struct {
	PackageCode    string
	DefinitionCode string
	OptionCode     string
	OptionName     string
	ShortCode      string
	Position       int16
}

type Warehouse struct {
	ID                pgtype.UUID
	CompanyID         pgtype.UUID
	BranchID          pgtype.UUID
	Code              string
	Name              string
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
	WarehouseType     string
	Address           string
	ResponsibleUserID pgtype.UUID
	UsesLocations     bool
	IsTransit         bool
	IsSystem          bool
}

type WarehouseTransfer struct {
	ID                     pgtype.UUID
	CompanyID              pgtype.UUID
	TransferNo             string
	SourceWarehouseID      pgtype.UUID
	DestinationWarehouseID pgtype.UUID
	TransitWarehouseID     pgtype.UUID
	State                  string
	RequestedBy            pgtype.UUID
	ApprovedBy             pgtype.UUID
	RequestedAt            pgtype.Timestamptz
	ApprovedAt             pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	ReceivedAt             pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	CancellationReason     string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Version                int64
	TransferType           string
}

type WarehouseTransferDiscrepancyResolution struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	TransferID     pgtype.UUID
	TransferLineID pgtype.UUID
	ResolutionType string
	Quantity       pgtype.Numeric
	Reason         string
	IdempotencyKey string
	ActorUserID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type WarehouseTransferLine struct {
	ID                         pgtype.UUID
	CompanyID                  pgtype.UUID
	TransferID                 pgtype.UUID
	LineNo                     int32
	ProductID                  pgtype.UUID
	VariantID                  pgtype.UUID
	LotID                      pgtype.UUID
	SerialID                   pgtype.UUID
	SourceLocationID           pgtype.UUID
	DestinationLocationID      pgtype.UUID
	Quantity                   pgtype.Numeric
	ShippedQuantity            pgtype.Numeric
	ReceivedQuantity           pgtype.Numeric
	DamagedQuantity            pgtype.Numeric
	DiscrepancyReason          string
	ProductCodeSnapshot        string
	ProductNameSnapshot        string
	VariantCodeSnapshot        string
	VariantDescriptionSnapshot string
}

type WarehouseTransferReservation struct {
	ID             pgtype.UUID
	CompanyID      pgtype.UUID
	TransferID     pgtype.UUID
	TransferLineID pgtype.UUID
	WarehouseID    pgtype.UUID
	ProductID      pgtype.UUID
	VariantID      pgtype.UUID
	LocationID     pgtype.UUID
	LotID          pgtype.UUID
	SerialID       pgtype.UUID
	Quantity       pgtype.Numeric
	State          string
	ReservedAt     pgtype.Timestamptz
	ConsumedAt     pgtype.Timestamptz
	ReleasedAt     pgtype.Timestamptz
}

type WorkScheduleDay struct {
	CompanyID         pgtype.UUID
	ScheduleVersionID pgtype.UUID
	TemplateID        pgtype.UUID
	Weekday           int16
	IsWorkday         bool
	StartsAt          pgtype.Time
	EndsAt            pgtype.Time
	EndsNextDay       bool
	BreakMinutes      int32
	PlannedMinutes    int32
}

type WorkScheduleTemplate struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type WorkScheduleTemplateVersion struct {
	ID            pgtype.UUID
	CompanyID     pgtype.UUID
	TemplateID    pgtype.UUID
	EffectiveFrom pgtype.Date
	EffectiveTo   pgtype.Date
	CreatedBy     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}
