// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package dbgen

import (
	"context"
)

const platformPing = `-- name: PlatformPing :one
SELECT 1::integer
`

func (q *Queries) PlatformPing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, platformPing)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
