// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	PlatformPing(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
