import type { EntityOption } from '$lib/components/varya/entity-picker-dialog';
import type { CommercialDocumentReference, CommercialResource, CommercialLineType } from './types';

export type ProductOption = EntityOption & {
  kind?: 'PHYSICAL' | 'SERVICE';
  unit?: string;
  code?: string;
  unitPrice?: string;
  baseUnitPrice?: string;
  taxRate?: string;
  taxIncluded?: boolean;
  variantsEnabled?: boolean;
};
export type VariantOption = EntityOption & {
  variantCode?: string;
  unit?: string;
  baseUnitPrice?: string;
};
export type WarehouseOption = EntityOption & { branchID?: string };
export type PartyOption = EntityOption & { code?: string };
export type SourceOption = EntityOption & {
  kind?: string;
  resource?: CommercialResource;
  documentNo?: string;
  href?: string;
  relationType?: string;
  status?: string;
};
export type ServerErrorDetail = { line?: number; field?: string; message: string };
export type ConversionAction = { target: CommercialResource; label: string };

export type DocumentLine = {
  id?: string;
  line_no?: number;
  line_type?: string;
  product_id?: string;
  product_name_snapshot?: string;
  product_code_snapshot?: string;
  variant_id?: string;
  variant_code?: string;
  variant_code_snapshot?: string;
  variant_attributes?: Record<string, unknown>;
  variant_attributes_snapshot?: Record<string, unknown>;
  warehouse_id?: string;
  warehouse_name?: string;
  warehouse_code?: string;
  unit_code?: string;
  quantity?: string;
  base_quantity?: string;
  conversion_factor?: string;
  ordered_quantity?: string;
  received_quantity?: string;
  invoiced_quantity?: string;
  accepted_quantity?: string;
  unit_cost?: string;
  unit_price?: string;
  tax_rate?: string;
  tax_snapshot?: { rate?: unknown; included?: unknown; [key: string]: unknown };
  tax_components_snapshot?: Array<{ rate?: unknown; included?: unknown; [key: string]: unknown }>;
  gross_amount?: string;
  discount_amount?: string;
  line_total?: string;
  tax_amount?: string;
  payable_amount?: string;
  description_snapshot?: string;
  description?: string;
  source_line_id?: string;
  source_receipt_line_id?: string;
  purchase_order_line_id?: string;
  goods_receipt_line_id?: string;
  remaining_fulfillment_quantity?: string;
  remaining_invoicing_quantity?: string;
  remaining_return_quantity?: string;
  remaining_invoicing_base_quantity?: string;
  remaining_return_base_quantity?: string;
};

export type DocumentRecord = {
  id: string;
  version?: number;
  status?: string;
  lifecycle_status?: string;
  fulfillment_status?: string;
  invoicing_status?: string;
  payment_status?: string;
  document_no?: string;
  order_no?: string;
  receipt_no?: string;
  invoice_no?: string;
  return_no?: string;
  branch_id?: string;
  default_warehouse_id?: string;
  default_warehouse_name?: string;
  default_warehouse_code?: string;
  warehouse_id?: string;
  warehouse_name?: string;
  warehouse_code?: string;
  party_id?: string;
  supplier_id?: string;
  currency_code?: string;
  currency?: string;
  document_date?: string;
  order_date?: string;
  receipt_date?: string;
  invoice_date?: string;
  return_date?: string;
  due_date?: string;
  valid_until?: string;
  exchange_rate?: string;
  notes?: string;
  source_kind?: string;
  source_document_id?: string;
  source_document_ids?: string[];
  fulfillment_at?: string;
  purchase_order_id?: string;
  goods_receipt_id?: string;
  goods_receipt_ids?: string[];
  source_document_no?: string;
  source_order_no?: string;
  source_receipt_id?: string;
  source_documents?: CommercialDocumentReference[];
  related_documents?: CommercialDocumentReference[];
  settlement?: {
    invoice_total?: string;
    returned_total?: string;
    effective_invoice_total?: string;
    collected_total?: string;
    paid_total?: string;
    amount_due?: string;
    amount_payable?: string;
    customer_credit?: string;
    supplier_credit?: string;
    payment_status?: string;
    return_status?: string;
    payments?: {
      id: string;
      document_no?: string;
      payment_kind?: string;
      transaction_date?: string;
      currency?: string;
      allocated_amount?: string;
    }[];
  };
  available_actions?: {
    can_edit?: boolean;
    can_delete?: boolean;
    can_post?: boolean;
    can_cancel?: boolean;
    can_create_return?: boolean;
    can_collect?: boolean;
    can_pay?: boolean;
    can_create_dispatch?: boolean;
    can_create_invoice?: boolean;
    can_create_edocument?: boolean;
  };
  branch_name?: string;
  subtotal?: string;
  discount_total?: string;
  tax_total?: string;
  grand_total?: string;
  payable_total?: string;
  total?: string;
  reason?: string;
  lines?: DocumentLine[];
  party_name?: string;
  party_code?: string;
  supplier_name?: string;
  supplier_code?: string;
};

export type LineDraft = {
  id?: string;
  lineType: CommercialLineType;
  product: ProductOption | null;
  variant: VariantOption | null;
  variants: VariantOption[];
  variantLoading: boolean;
  variantError: string;
  variantRequestKey?: number;
  variantSnapshot?: boolean;
  warehouse: WarehouseOption | null;
  unitCode: string;
  quantity: string;
  conversionFactor: string;
  unitPrice: string;
  baseUnitPrice: string;
  discountRate: string;
  taxRate: string;
  taxIncluded: boolean;
  persistedTotal?: string;
  description: string;
  orderedQuantity?: string;
  receivedQuantity?: string;
  invoicedQuantity?: string;
  acceptedQuantity?: string;
  remainingFulfillmentQuantity?: string;
  remainingInvoicingQuantity?: string;
  sourceRemainingQuantity?: string;
  sourceLineID?: string;
  purchaseOrderLineID?: string;
  goodsReceiptLineID?: string;
  manualPrice: boolean;
};

export type DocumentForm = {
  documentNo: string;
  party: PartyOption | null;
  branchID: string;
  branchName: string;
  defaultWarehouse: WarehouseOption | null;
  documentDate: string;
  dueDate: string;
  validUntil: string;
  currency: string;
  exchangeRate: string;
  notes: string;
  sourceDocumentID: string;
  sourceDocument: SourceOption | null;
  sourceDocuments: SourceOption[];
  sourceKind: string;
  reason: string;
};
